default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: helloRailsBackrnd
  password: 67112

development:
  <<: *default
  database: hello_rails_backend_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: hello_rails_backend_test

production:
  <<: *default
  database: hello_rails_backend_production
  username: helloRailsBackrnd
  password: 67112
